apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisdb
  labels:
    app: redisdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisdb
  template:
    metadata:
      labels:
        app: redisdb
    spec:
      containers:
      - name: redisdb
        image: redis
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redisdb-service
spec:
  type: NodePort
  selector:
    app: redisdb
  ports:
    - port: 8022
      targetPort: 6379
      nodePort: 30001